### ISSUE TITLE
Package no longer on CRAN

### ISSUE THREAD

**Issue by Carina8899** [ropensci/weathercan#103]
Hello, I tried to download the weathercan package from CRAN, but the page shows that "Package ‘weathercan’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive."
Can anyone tell me what happened?

**Comment by steffilazerte** [comment]
Argh, I have no idea. I'll try to figure out why it's been removed

**Comment by steffilazerte** [comment]
So looking into it, I don't have much more information, but it looks like weathercan started failing checks on Linux for patched and devel versions of R. 

I'll start working on a fix and will hopefully have it figured out soon. 

In the meantime, you're welcome to download the package from the GitHub site. The master branch is the same version that was on CRAN. Go to the [main repository page](https://github.com/ropensci/weathercan) and follow the instructions for the developmental version. 

I'll chime in here when I've submitted to CRAN again, so you can then install the 'official' version. Thanks for reporting!

**Comment by Carina8899** [comment]
Hi Steffi, thank you so much for looking into it. I just downloaded the developmental version of the package and it works well!

**Comment by steffilazerte** [comment]
We're back on CRAN so you should be able to update to the CRAN version now, thanks for you patience
