### ISSUE TITLE
Error when trying to access weather data in R ---->   SEC_E_ILLEGAL_MESSAGE (0x80090326)

### ISSUE THREAD

**Issue by amcilraithRRC** [ropensci/weathercan#104]
## Expected Behavior
 Weather data should download in R

## Current Behavior

#install.packages("weathercan")
#install.packages("lutz")
#install.packages("sf")
library("weathercan")
library("lutz")
library("sf")
s <- stations_dl()
weather_dl(station_ids = 51097, start = "2020-10-01", end = "2020-10-08",interval="hour")
Error: Problem with `mutate()` input `html`.
x schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
i Input `html` is `purrr::map(...)`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `html`.
x schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
i Input `html` is `purrr::map(...)`.
Backtrace:
  1. weathercan::weather_dl(...)
 26. base::.handleSimpleError(...)
 27. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.

## Steps to Reproduce (for bugs)

See above

1. 
2.
3.
4.

## Context

Unable to use weathercan

## Your Environment

Windows 10

**Comment by steffilazerte** [comment]
I can't seem to reproduce this on Linux 20.04 nor on Windows 10. Travis CI is also fine but weirdly appveyor is failing with the same message (I've also received an email from someone regarding the same issue).

@boshek Can you reproduce this on your machine?

I'm wondering if it's a company/government network issue. @amcilraithRRC are you on a personal computer or work computer?

**Comment by amcilraithRRC** [comment]
Hi Steffi;
I am using a college computer on my home network, Shaw as a provider and all firewalls are turned off.
Will try loading up weathercan on another computer to see what happens.
It is interesting that the function to download stationIDs works but the one for downloading data does not.
Will keep you posted.
Alex

**Comment by amcilraithRRC** [comment]
Hi Steffi;
Tried on another computer that I use for research and it does work.
Notes:

-          On the college laptop, I upgraded R and R-studio to the latest versions (R is 4.0.2) since my version was too old to properly load weathercan and its dependencies.

-          On the other machine, I am running R 3.5.2.
Not sure if this is relevant.
Alex

**Comment by steffilazerte** [comment]
Thanks for trouble shooting! For the laptop that does work, is it a personal laptop or another college/work laptop? I'm trying to figure out if this is a permissions problem with curl, which might be funny on institution computers.

**Comment by amcilraithRRC** [comment]
The computer that does work is a personal machine.
Is there a way that I can debug to see what the problem is?
I teach programming and networks, so I am interested in doing some digging. ;)

**Comment by boshek** [comment]
Here the url that your query is ultimately accessing: https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10

One step is to see if that even works in the browser.

**Comment by steffilazerte** [comment]
That'd be great! These kinds of problems just make me wanna cry!

As @boshek pointed out, a good place to start is simply with the link in your browser. It should initiate a csv download.

Also, here is a simple example with expected output of what weathercan does under the hood using the httr package (which uses the curl package). If the url doesn't work then none of this will, but if url does work, then the problem might be in httr/curl (I'm not sure where to go exactly from there, but let me know if you have any questions). 

```
library(httr)

q <- list(format = "csv", stationID = 51097, timeframe = 1, submit = 'Download+Data', Year = 2020, Month = 10)
data <- GET(url = getOption("weathercan.urls.weather"),  query = q)

data
# Response [https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10]
#  Date: 2020-10-09 17:42
#  Status: 200
#  Content-Type: application/force-download
#  Size: 83.4 kB
# <BINARY BODY>

data$request$url
# [1] "https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10"

content(data, as = "text")
# No encoding supplied: defaulting to UTF-8.
# [1] "﻿\"Longitude (x)\",\"Latitude (y)\",\"Station Name\",\"Climate ID\",\"Date/Time\",\"Year\",\"Month\",\"Day\",\"Time\",\"Temp (°C)\",\"Temp Flag\",\"Dew Point Temp (°C)\",\"Dew Point Temp Flag\",\"Rel Hum (%)\",\"Rel Hum Flag\",\"Wind Dir (10s deg)\",\"Wind Dir Flag\",\"Wind Spd (km/h)\",\"Wind Spd Flag\",\"Visibility (km)\",\"Visibility Flag\",\"Stn Press (kPa)\",\"Stn Press Flag\",\"Hmdx\",\"Hmdx Flag\",\"Wind Chill\",\"Wind Chill Flag
```

**Comment by amcilraithRRC** [comment]
This URL works (Firefox 81.0.1); the problem appears to be in how R is trying to access the site.
When I had initially accessed data I used this sort of link from the EC website and it worked.
I will look at info in Steffi’s email.

**Comment by amcilraithRRC** [comment]
Same script, different results from two computers.





Output from "good” computer:

> library(httr)

Warning message:

package ‘httr’ was built under R version 3.5.3

>

> q <- list(format = "csv", stationID = 51097, timeframe = 1, submit = 'Download+Data', Year = 2020, Month = 10)

>

> data <- GET(url = getOption("weathercan.urls.weather"),  query = q)

>

> data

Response [https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10]

  Date: 2020-10-09 17:56

  Status: 200

  Content-Type: application/force-download

  Size: 83.4 kB

<BINARY BODY>



Output from "bad” computer (had to do screen capture for this one):

[cid:image002.png@01D69E3D.124DA380]

……………code dump continues……..

**Comment by boshek** [comment]
`read.csv` doesn't use the R curl library (pretty sure). Does this work?

`read.csv("https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10")`

**Comment by amcilraithRRC** [comment]
[cid:image002.png@01D69E3D.995115B0]

On problem computer, it does not work.

**Comment by boshek** [comment]
@amcilraithRRC can you also give the error messages please? Is it the same error message?

**Comment by amcilraithRRC** [comment]
I attached an image in the last email; maybe it did not come thru.
Will attach as jpg. For some reason I am not being able to copy the console text on this “problem” machine.
Alex

**Comment by steffilazerte** [comment]
If you want to include an image, I think you'll need to go to GitHub issues directly and add it by dragging/dropping or pasting them into the window here.

**Comment by amcilraithRRC** [comment]
![ReadCSV_Capture](https://user-images.githubusercontent.com/72586000/95620463-d7808280-0a35-11eb-9312-0f7a5655a7a0.JPG)


Added image of error - Alex

**Comment by amcilraithRRC** [comment]
Tried a different URL and I did get a response from the server to a simple http_get:

library(httr)
myURL <- "http://www.rrc.ca"
GET(url=myURL)

**Comment by steffilazerte** [comment]
Argh I'm at a bit of a loss!

**Comment by amcilraithRRC** [comment]
I will play with it a bit as i find inspiration. Would be nice to know root cause in case any one else runs into it. 
Thanks for all the help so far!

**Comment by steffilazerte** [comment]
Thank you for putting in the effort, it's really nice to have the assistance :)

**Comment by boshek** [comment]
Really just throwing some mud at the wall now but does this in browser work:
https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=txt&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10

or this directly with {curl}:

curl::curl_fetch_memory('https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=txt&stationID=51097&timeframe=1&submit=Download%2BData&Year=2020&Month=10')

**Comment by amcilraithRRC** [comment]
![image](https://user-images.githubusercontent.com/72586000/95641108-06165180-0a66-11eb-94de-bf92ace8b9ba.png)

Hello, I think I am finding some bread crumbs,  I captured the packets being sent from my computer to the weathercan server. It appears that the weathercan server is rejecting the TLS handshake as it comes from R and then immediately resets the connection. I will try capturing the same connection attempt on the other computer and see what the difference(s) are.

**Comment by steffilazerte** [comment]
I'm excited to report that I think I've figured out a fix for those users experiencing problems.

Delving into the [`curl`](https://jeroen.cran.dev/curl/) package's vignette for [Proxies and Certificates on Windows Networks](https://cran.r-project.org/web/packages/curl/vignettes/windows.html), I found that there are two SSL backends for Windows: OpenSSL and Windows Secure Channel. By default `curl` uses the Windows Secure Channel which is supposed to be best, but doesn't quite have the full functionality of OpenSSL.

My best guess is that something changed on the ECCC server that required a functionality not provided by Windows Secure Channel. When I forced my windows testing platform (AppVeyor) to use OpenSSL, all my tests cleared.

If you would like to try this, you'll have to add the following to your .Renviron file (which is loaded during R's startup):

`CURL_SSL_BACKEND=openssl`

If you're unsure how to edit your .Renviron file, you can use the `usethis` package to find/create and open it for you:

```
install.packages("usethis")
usethis::edit_r_environ()
```

**Disclaimer:** I don't *think* there are security drawbacks for doing this, but I'm not a network specialist by any stretch! 

If you decide to give this a try, let me know how it goes!

**Comment by tspeidel-suncor** [comment]
I'm getting the same error. The `.Renviron` change did not work.

**Comment by boshek** [comment]
Just noticed that you are running Windows 7. Any chance you can try on Windows 10 machine on the same network?

**Comment by steffilazerte** [comment]
Drat, the change worked for three others else affected (although I'm not sure about @amcilraithRRC).

1. Can you try running: `curl::curl_version()` and share the output with us. This should help figure out which SSL backends you have and which one you're using.

2. Do you use a company proxy?

**Comment by tspeidel-suncor** [comment]
> 1. Can you try running: `curl::curl_version()` and share the output with us. This should help figure out which SSL backends you have and which one you're using.

I just installed the latest `curl`. Here's the output:

`R> library(curl)
Using libcurl 7.64.1 with Schannel
R> CURL_SSL_BACKEND=openssl
Error: object 'openssl' not found
R> curl::curl_version()
$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps" 
[10] "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE`

**Comment by ebourlon** [comment]
Hi,
Could it be a security certificate issue with climate.weater.gc.ca again
(October 2019 issue)?
E.

**Comment by tspeidel-suncor** [comment]
> Just noticed that you are running Windows 7. Any chance you can try on a Windows 10 machine on the same network?

Windows 10 has no issues. Unfortunately, I can only work in Win 7.

**Comment by steffilazerte** [comment]
@ebourlon It could be, unfortunately I'm at a complete loss now.

@tspeidel-suncor You may be better luck asking on the [curl](https://jeroen.cran.dev/curl/) page?

Sorry 😞

**Comment by amcilraithRRC** [comment]
Hi;
I did find out that the machine that does not work for me is Windows 8.1. The working one is Windows 10.
Have been working on other projects, but will poke at this one again soon.
Alex

**Comment by jeroen** [comment]
As a workaround for SSL problems on old versions of windows, you can switch to the openssl backend by setting

````
CURL_SSL_BACKEND=openssl
```

In your `~/.Renviron` file. See [this vignette](https://cran.r-project.org/web/packages/curl/vignettes/windows.html) for more details.

**Comment by steffilazerte** [comment]
We did suggest that as a possible solution, I think @tspeidel-suncor's problem is that this solution didn't work for them. Any reason why it wouldn't?

**Comment by jeroen** [comment]
I think he didn't set it in the correct file, because the error suggests it is still using windows native ssl, not openssl.

@tspeidel-suncor can you run this in R:

```r
writeLines("CURL_SSL_BACKEND=openssl", "~/.Renviron")
```

Make sure you restart R after that, because the change gets activated when the curl package is first loaded.

**Comment by tspeidel-suncor** [comment]
> I think he didn't set it in the correct file, because the error suggests it is still using windows native ssl, not openssl.
> 
> @tspeidel-suncor can you run this in R:
> 
> ```r
> writeLines("CURL_SSL_BACKEND=openssl", "~/.Renviron")
> ```
> 
> Make sure you restart R after that, because the change gets activated when the curl package is first loaded.

That's correct, I did try adding openssl to my `.Renviron` to no avail. I tried again using the `writelines()`, but still get ther error:

```
> kam <- weather_dl(station_ids = 51423, start = "2018-02-01", end = "2018-04-15")
Error: Problem with `mutate()` input `html`.
x schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
i Input `html` is `purrr::map…`.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by amcilraithRRC** [comment]
I tried it without reloading R and it failed.
After reloading R, it works perfectly!
Many thanks,
Alex
(Using Windows 8.1)
