### ISSUE TITLE
Error when downloading weather data

### ISSUE THREAD

**Issue by a2grotto** [ropensci/weathercan#107]
I am having troubles downloading weather data using weathercan::weather_dl(). 
I used this same code about a month ago and everything worked fine.
All packages are updated.

`ns.2004 <- weathercan: :weather_dl(station_ids = c(6923, 42243),
start = '2004-04-01', end = '2004-07-31', interval = "hour")`

Error Message
```2 parsing failures.  row col  expected    actual         file
  9  -- 2 columns 1 columns literal data
  9  -- 2 columns 1 columns literal data
Error: Problem with `mutate()` input `time`.
x Column `time` not found in `.data`
i Input `time` is `as.POSIXct(.data$time, tz = "UTC")`.


`Session info 
 setting  value  
version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Canada.1252         
 ctype    English_Canada.1252         
 tz       America/New_York            
 date     2021-01-14 `

**Comment by steffilazerte** [comment]
Yes, this is expected as ECCC update the weather data this morning. 

I'm working on a fix now and hope to have it to CRAN this evening. The upside is that one of the changes ECCC made was including Precipitation for hourly data!

**Comment by steffilazerte** [comment]
v0.5.0 is now on CRAN and should fix this problem
