### ISSUE TITLE
Problem with `mutate()` input `html`.

### ISSUE THREAD

**Issue by FraserHemis** [ropensci/weathercan#108]
## Expected Behavior

weather_18 <- weather_dl(station_id, interval='hour')
I was trying to download data from a station (10868). I was expecting the data.

## Current Behavior

Erreur : Problem with `mutate()` input `html`.
x schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
i Input `html` is `purrr::map(...)`.

**Comment by boshek** [comment]
This is a duplicate of #104

@FraserHemis have you tried any of the troubleshooting outlined in that thread?
