### ISSUE TITLE
`vcr::vcr_test_path` issue from vcr v1.0.0

### ISSUE THREAD

**Issue by sckott** [ropensci/weathercan#122]
With the latest version of `vcr` just up to CRAN I unfortunately caused breaking changes for some packages depending on `vcr`. The function `vcr_test_path` is the issue. The change to that function worked for some, but it apparently has broken other packages. 

We have a proposed fix at https://github.com/ropensci/vcr/pull/236 Can you install that fork `remotes::install_github("dpprdan/vcr@fix/test_path")` and see if that fixes the problem?

**Comment by sckott** [comment]
Great, thanks for testing that out. I'll ping here again when i've submitted a new version to CRAN

**Comment by sckott** [comment]
A new version of `vcr` is on CRAN https://cloud.r-project.org/web/packages/vcr/ - CRAN checks for your package should be fixed soon once they are using the new version of `vcr`.

**Comment by steffilazerte** [comment]
Thanks!

**Comment by sckott** [comment]
vcr working now for you?

**Comment by steffilazerte** [comment]
Well enough 😁 most of my tests still use it to a certain degree, but I am afraid to touch sometimes 😅

**Comment by sckott** [comment]
> I am afraid to touch sometimes 

b/c of vcr or something else? if vcr, anything I can change in vcr to help with that?

**Comment by steffilazerte** [comment]
I think it's good now. I think my biggest problem was figuring out how vcr worked when running tests interactively. Either it's improved (🙏🏼) or I got better at understanding! I'll let you know if I run into problems which are vcr related. Thanks for checking in!

**Comment by sckott** [comment]
yeah the interactive user experience is not ideal for sure. thanks for the feedback
