### ISSUE TITLE
Update docs to reflect installing weathercan from the R-universe

### ISSUE THREAD

**Issue by ecwiebe** [ropensci/weathercan#123]
## Expected Behavior

weathercan should (?) be available on cran...
## Current Behavior

weathercan is not available on cran 
## Steps to Reproduce (for bugs)

1. try to download weathercan from cran
## Possible Solution

Fix the "repeated policy violations"?
## Context

https://cran.r-project.org/web/packages/weathercan/index.html reports 

Package ‘weathercan’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2021-07-04 for repeated policy violation.
A summary of the most recent check results can be obtained from the check results archive.
Please use the canonical form https://CRAN.R-project.org/package=weathercan to link to this page.

**Comment by steffilazerte** [comment]
Hi @ecwiebe,

Thanks for your issue submission.

Yes weathercan was archived (again). I'm not sure exactly what it was that (again) violated the policies, but it is certainly related to the "not accessing online resources during CRAN checks" policy. 

With a package like weathercan that is designed to access online resources it's really hard to adequately test the package and not ever touch online resources. I have added lots of complexity to the tests and examples to either skip them on CRAN, use 'recorded' tests via VCR, or 'mock' tests via mockery. 

Unfortunately, as much as I am trying to not violate policies, it happens. CRAN is becoming increasing impatient (this is not the first time they have archived weathercan with no warning and no notification to me). 

While I plan to continue maintaining weathercan and fixing bugs, I no longer have the time to add complexity only to avoid tests and policy violations on CRAN. Therefore I've decided to no longer maintain weathercan on CRAN.

However, you can download weathercan via the remotes packages:

```
install.packages('remotes')
remotes::install_github("ropensci/weathercan")
```

And as soon as I get a moment, I plan to set up an [R Universe ](https://ropensci.org/r-universe/) which will make it possible to install weathercan without remotes. 

I'll be updating the README and docs soon to reflect this.

Sorry 😞

**Comment by ecwiebe** [comment]
I tried this and did eventually get it to succeed. It warned me about the stations list needing updating which requires some gdal developer packages (not R) and that needs me to update ports on my Mac and it’s turned into a whole thing.

Just another Monday!

Thanks,

Ed

**Comment by steffilazerte** [comment]
Ah good to know. The new version allows you to update your stations list directly (old version didn't), and then prompts you to get the newest version. I'll see about making that a little less obtrusive, as you technically don't really need to do it unless you need bleeding edge stations lists.

I'll also see about automatically updating the list elsewhere (online), so perhaps you could download the list prepared by weathercan. A bit less bleeding edge, but still updated and requires fewer dependencies. 

Thanks for the feedback!

**Comment by boshek** [comment]
One note is that the ropensci already has a r-universe so weathercan is automatically built there. You can install it like so:

`install.packages("weathercan", repos = "https://dev.ropensci.org")`

**Comment by steffilazerte** [comment]
Right! I forgot! Great point :grin:

**Comment by steffilazerte** [comment]
And I have changed my mind and am planning on fixing all the examples/tests to no longer run on CRAN so we can put it back, it'll be a little while before I get to this though!

**Comment by boshek** [comment]
Could make use of `@examplesIf` and only run them outside of CRAN too

**Comment by steffilazerte** [comment]
Yup, that's the plan! skip_on_cran(), @examplesIf, and compile the vignettes before hand :grin:

**Comment by steffilazerte** [comment]
Okay, docs are updated AND weathercan is back on CRAN (hopefully for a while this time!)
