### ISSUE TITLE
Installing using `devtools`

### ISSUE THREAD

**Issue by gilberto-sassi** [ropensci/weathercan#127]
Hi guys, 

I tried to install `weathercan` using `devtools::install_github("ropensci/weathercan", build_vignettes = TRUE) `, and worked :). But when I tried to load the package with `library(weathercan)`, I got the following messagens:

```r
Error: package or namespace load failed for ‘weathercan’:
 .onLoad failed in loadNamespace() for 'weathercan', details:
  call: is_old_cache(cache)
  error: lazy-load database '/usr/local/lib/R/site-library/cachem/R/cachem.rdb' is corrupt
In addition: Warning message:
In is_old_cache(cache) : internal error -3 in R_decompress1
```

I am new to `R`, I have no idea how to solve this error. I am using Ubuntu, and R version 4.1.1.

I apologize if my issue is too simple, and for my poor english.

Gilberto.

**Comment by steffilazerte** [comment]
Hi @gilberto-sassi!

Sometimes all you need to do is restart R after installing the package and try again. If that doesn't work, try updating the package that seems to be having trouble (cachem) `install.packages("cachem")`

If *that* doesn't work, try updating all your packages `remotes::update_packages()`. 

Let us know how it goes!

**Comment by gilberto-sassi** [comment]
It worked!

Thank you!

Gilberto.

**Comment by steffilazerte** [comment]
Great!
