### ISSUE TITLE
pkgdown error on docs server

### ISSUE THREAD

**Issue by maelle** [ropensci/weathercan#135]
https://github.com/r-universe/ropensci/actions/runs/4386295506/jobs/7680161044

**Comment by maelle** [comment]
I don't think what the log shows in the error (it's the deprecation _warning_). I can't explore right now.

**Comment by steffilazerte** [comment]
I know what this is, I'm surprised I haven't noticed before, thanks for pointing it out!

**Comment by maelle** [comment]
locally I was able to build the website!

**Comment by maelle** [comment]
> I know what this is, I'm surprised I haven't noticed before, thanks for pointing it out!

So what is it, actually? I'm surprised it worked locally but not on GHA.

**Comment by maelle** [comment]
@steffilazerte Friendly reminder :smile_cat:

**Comment by maelle** [comment]
Side-note, on https://ropensci.github.io/weathercan/articles/mapping.html the CSS rules you add (I guess?) make the logo too big.

**Comment by maelle** [comment]
@steffilazerte what if you try with the dev version of dependencies? 
Is the code building the website dependent on an environmental variable called CI (it is TRUE on GitHub Actions but it is unset on R-universe).
Thanks @jeroen for the ideas

**Comment by steffilazerte** [comment]
I'll take a look, thanks

**Comment by steffilazerte** [comment]
Tried these options and it still works locally. Fixed by avoidance 😅 . Move the mapping article to my [website](https://steffilazerte.ca/posts/weathercan-mapping/) and removed from the docs (it wasn't really a weathercan specific tutorial). 

We'll see if that works on R-Universe now!

**Comment by maelle** [comment]
Yes, all green on https://ropensci.r-universe.dev/builds :tada: 

That's a pretty smart fix. :grin:
