### ISSUE TITLE
where in the package is the stations object still used

### ISSUE THREAD

**Issue by maelle** [ropensci/weathercan#139]
The rOpenSci docs build gets

```
The internal `stations` data has been deprecated in favour of the function `stations()`.
See ?stations for more details.
```

**Comment by maelle** [comment]
oh wait it's a startup message, I hadn't noticed that.

**Comment by maelle** [comment]
what about https://ropensci.org/blog/2023/04/21/ropensci-news-digest-april-2023/#deprecated-data-in-a-package-with-delayedassign

**Comment by maelle** [comment]
Removing old stuff you assume is not used, and seeing what happens, is a strategy mentioned in https://www.goodreads.com/book/show/54716655-kill-it-with-fire :grin:

**Comment by steffilazerte** [comment]
Removed in v0.7.1 (e6015a0949dd548258b2d42168cbdd706bafdb07)
