### ISSUE TITLE
Add suggested citation including ECCC website and weathercan

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/weathercan#36]

**Comment by boshek** [comment]
Where are you thinking this would go? Is it something like this: https://github.com/bcgov/tidyhydat#citation

**Comment by steffilazerte** [comment]
Yes, exactly!

Perhaps with an additional comment on how to cite the ECCC data as well?

**Comment by boshek** [comment]
Seems like this could be closed given what you've done here:

https://github.com/ropensci/weathercan/blob/9d8df84cb9e17e77bd4b4ff417e54b151c01c9a8/inst/CITATION#L1-L18
