### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by boshek** [ropensci/weathercan#50]
The R version of `weathercan` is likely too restrictive. Using this [app](http://shiny.andyteucher.ca/shinyapps/rver-deps/), shows that we likely only need a version of 3.2.0. Even to be conservative we may considered only requiring 3.3.0 so that older versions of R can run weathercan.

**Comment by steffilazerte** [comment]
Very cool shiny app!
Good idea, I dropped the version down and added a couple of old release checks to travis ci and appveyor.
