### ISSUE TITLE
dplyr exports all the required tibble functions so we can remove the tibble dependency. 

### ISSUE THREAD

**Issue by boshek** [ropensci/weathercan#55]
For instance this:

https://github.com/ropensci/weathercan/blob/3b8d291c25f68cb687f6fca34643b16d9c2724be/R/interpolate.R#L72-L74

Can be changed to this:

```
  ## Convert to tibbles for consistency
  data <- dplyr::as_tibble(data)
  weather <- dplyr::as_tibble(weather)
```

FWIW I realize that it was me who did this in the first place 🤦‍♂️

**Comment by boshek** [comment]
Push to `dev-steffi`? Or do you want to review a pull request?

**Comment by steffilazerte** [comment]
No that's fine, go ahead and push to the dev branch
