### ISSUE TITLE
Is this something we want to support in weathercan?

### ISSUE THREAD

**Issue by boshek** [ropensci/weathercan#63]
A way of dissemination data from ECCC:

https://dd.meteo.gc.ca/climate/doc/observations/README_climate.txt

With the data being here:

https://dd.meteo.gc.ca/climate/observations/

It would require a bit of work under the hood but it might at least even be worth a speed test. Haven't fully explored the datamart for this product so it may not be fully appropriate.

**Comment by steffilazerte** [comment]
Definitely worth checking out for data normals! They have them as single csv files which would make it much easier to access. For daily and monthly values it looks as if the files are in the same format, so we'd only have to change the script accessing the file, and that might be faster. No hourly data though :-/

Another place that might need changes is the parts of the script that identify missing dates/files/etc. but definitely worth a try if it's faster.

**Comment by boshek** [comment]
Right normals! This option for normals is much better than anything we brainstormed in #38. Maybe a good approach is to close this issue and address #38 with these .csvs? Leave the monthly and daily data for another time?

**Comment by steffilazerte** [comment]
I like it!
