### ISSUE TITLE
Env Canada station location precision

### ISSUE THREAD

**Issue by nadrojordan** [ropensci/weathercan#64]
I was wondering if there is any way to got lat/lon coordinates at a higher precision than 2 decimal places, which is an error of plus or minus 1.1km or less.  

Thank you, this package has proven invaluable to our research team. 

J

**Comment by steffilazerte** [comment]
I'm glad `weathercan` has proven useful. Unfortunately lat/lon are returned to with same degree of precision as they're received from ECCC. I've looked around and all historical weather data from ECCC (i.e. website, ftp, etc) have limited lat/lon. If you have specific stations in mind, I'm sure you could ask them for more details?
Good luck!
