### ISSUE TITLE
Memoise download functions

### ISSUE THREAD

**Issue by boshek** [ropensci/weathercan#67]
We should consider adding a memoise ability to any download function.

This cache's the output in a session so that unless the parameters have changed, identical download calls will only be downloaded once per session. It is fairly easy to implement and can provide a reasonable buffer to repeated identical downloads.

Here is the memoise package: https://github.com/r-lib/memoise

**Comment by steffilazerte** [comment]
Excellent idea

**Comment by boshek** [comment]
I now wonder if this isn't the best solution as it could have some odd behaviours with such high frequency updates as the weather data. Something like this would be better but it isn't on CRAN: https://github.com/ropensci/bowerbird

**Comment by maelle** [comment]
A WIP package by @sckott might be relevant: https://github.com/ropensci/webmiddens

**Comment by steffilazerte** [comment]
For now we're using memoise, with a cache expiration of 24hrs. But I'm waiting on webmiddens for sure!
