### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/weathercan#80]
👋  as part of preparing an rOpenSci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And whatever metric is most relevant for this data?

**Comment by steffilazerte** [comment]
An extremely rough estimate would be ~ 110 GB (I had fun, if you're interested: <http://ropensci.github.io/weathercan/articles/articles/data.html>). Considering this is text data (so small), I think that's pretty impressive!

As for metric, well perhaps years would be the most interesting? Or time in general? For this data, ignoring the climate normals, we have up to 397,671 years worth of data (summed across different stations and within stations at different time scales).

All of these values are possibly an overestimate, as they're calculated from the start and end years of a station, which may not represent a whole year, and which don't account for gaps in the data record.

Is this something of what you were looking for?

**Comment by sckott** [comment]
Thanks very much, that works!  We're going for rough estimates here since it's just for informational purposes, thanks for taking the time on this! 

What is the earliest year that data is present? So we can get a span

**Comment by steffilazerte** [comment]
http://ropensci.github.io/weathercan/articles/articles/data.html

Earliest year was 1840 in Toronto! That station didn't close down until 2017! For reference, there were 365 stations which were active prior to 1900. Actually a pretty fun exercise!

**Comment by sckott** [comment]
great, thanks very much @steffilazerte ! and i'm glad it was fun 😸
