### ISSUE TITLE
ECCC Format change 

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/weathercan#83]
ECCC Changed the format of the historical weather data yesterday, this will require a small tweak to the package to get us back on track.

**Comment by steffilazerte** [comment]
We're on CRAN now, you can update with `install.packages("weathercan")`. 
Good luck!

**Comment by AmeerDotHydro** [comment]
Hello, I am getting the following error while trying to install the updated version. please suggest a way forward. Thank you.
`install.packages("weathercan")`

> Installing package into ‘C:/Users/AMUH/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘weathercan’ is not available (for R version 3.5.2)

**Comment by steffilazerte** [comment]
Hi Ameer, thanks for the heads up, I just submitted a new version to CRAN and was told that everything was fine. Something must have gone wonky. I'll contact CRAN and see what's up and will let you know!

**Comment by steffilazerte** [comment]
weathercan v0.3.3 is up on CRAN, thanks for you patience!

**Comment by clairervh** [comment]
Hi 
We are using R version 4.02 and receive the message R is not available for this version. Will there be any update for this version or R? 
Regards,
Claire

**Comment by boshek** [comment]
👋 @clairervh 

`weathercan` currently isn't up on CRAN. However it still can be installed using this command:

`install.packages("weathercan", repos = "https://dev.ropensci.org")`

**Comment by clairervh** [comment]
Thanks very much, that worked!
