### ISSUE TITLE
Can not download with weather_dl

### ISSUE THREAD

**Issue by WatershedFlow** [ropensci/weathercan#84]
I try to download daily data with following code:

Regina<- weather_dl(station_ids = 28011, start = "2019-02-01", interval = "day", quiet = TRUE)

then I got this error without anything else happened, i.e., no data downloaded. 
Error in 1:grep("Date/Time", preamble$V1) : argument of length 0

Thanks for your help.

**Comment by steffilazerte** [comment]
Yes, unfortunately this is because of issue #83, ECCC changed the format of their downloads yesterday. I have a fix in the works, and it should be ready for testing soon. Thanks!

**Comment by steffilazerte** [comment]
@WatershedFlow , if you get the chance to test it, the fix has been posted to the master branch:

```
install.packages("remotes")
remotes::install_github("ropensci/weathercan")
```

Then test as you would normally:

```
library(weathercan)
kam <- weather_dl(station_ids = 51423, start = "2016-01-01", end = "2016-02-15")
kam
```

**Comment by steffilazerte** [comment]
We're on CRAN now, you can update with `install.packages("weathercan")`. 
Good luck!
