### ISSUE TITLE
Error received when calling weather_dl()

### ISSUE THREAD

**Issue by macsmith26** [ropensci/weathercan#85]
Hello,

I received the following error when calling the example fctn to download weather data `weather_dl(station_ids = 51423, start = "2018-02-01", end = "2018-04-15")`:

`Error in 1:grep("Date/Time", preamble$V1) : argument of length 0`

**Comment by steffilazerte** [comment]
Hi @macsmith26 can you confirm that you're using the most recent version of `weathercan` (v0.3.1)?

```
packageVersion("weathercan")
# [1] ‘0.3.1’
```

If you're using v0.3.0, you'll need to update 

```
install.package("weathercan")
packageVersion("weathercan") # double check
```

**Comment by macsmith26** [comment]
Rookie mistake on my part. My version was 0.2.8. Updated and everything is working fine again, thanks!
