### ISSUE TITLE
Error with using weather_dl()

### ISSUE THREAD

**Issue by emhodg** [ropensci/weathercan#89]
There seems to be an issue with the weather_dl() function, when I use it to pull data from a specific station, e.g. `weather_dl(station_ids = c(1648), start = "1990-01-01", end = "1991-01-01", interval = "day")`

I get the following error:

`Error in stringr::str_subset(., "^\r$", negate = TRUE) : 
  unused argument (negate = TRUE)`

I just downloaded the package, so am using the most recent version. Any suggestions would be appreciated. Thank you! I am very excited to try this package out.

**Comment by boshek** [comment]
👋 @emhodg  

Can you please run sessionInfo() and paste that output here? I am unable to reproduce this - that is this bit of code works for me with R 3.61 and weathercan 0.3.1.

**Comment by ebourlon** [comment]
Looks like you have an old version of stringr installed. It happended to me
when I installed the current weathercan package. The negate argument was
added in stringr 1.4.0. You could update to the latest version of stringr
by running: install.packages("stringr").
E.

**Comment by steffilazerte** [comment]
That's really good to know! I'll increase the `stringr` version dependency to 1.4.0 to hopefully avoid future confusion. Thanks @ebourlon! @emhodg, can you confirm that this fixes your problem?

**Comment by emhodg** [comment]
Yes that is the fix! Thank you all for such quick responses. Much appreciated.
