### ISSUE TITLE
Package no longer on CRAN

### ISSUE THREAD

**Issue by jjvenky** [ropensci/weathercan#92]
CRAN now shows than weathercan has been removed https://cran.r-project.org/web/packages/weathercan/index.html

"Archived on 2020-01-10 for policy violation."

Any idea what happened?

**Comment by steffilazerte** [comment]
Yes, there was a miscommunication, the package had passed checks and was on it's way to CRAN, but at some point between Jan 7th and 10th, it failed again. For some reason I didn't get another notice about this failure so it was removed. I've been away at a funeral, so haven't been able to address the problems. I'm now back, though, so hopefully I'll be able to get it back on CRAN within a day or so! Thanks for checking in.

**Comment by jjvenky** [comment]
Thanks for the update @steffilazerte. Sorry about the funeral.

**Comment by boshek** [comment]
Remember that the package can still be installed via:

```
install.packages("devtools") # If not already installed
devtools::install_github("ropensci/weathercan") 
```

**Comment by AmeerDotHydro** [comment]
Thanks for the update- would the version through `devtools` would have updated data?

**Comment by boshek** [comment]
@AmeerDotHydro Can you be more specific? weathercan itself stores very little data and accesses most of it via the web

**Comment by AmeerDotHydro** [comment]
@boshek - sorry for the confusion. I just tested the package and all looks good to me.

**Comment by steffilazerte** [comment]
`weathercan` v0.3.3 is up on CRAN, thanks for you patience!
